version: "3.8"

services:
  api:
    build:
      context: api
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@postgres/db_name
      - RABBITMQ_URL=amqp://user:password@rabbitmq
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - rabbitmq
      - keycloak
      - redis

  media-server:
    build:
      context: media-server
      dockerfile: ./apps/media-server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq
    deploy:
      replicas: 1 # Adjust the number of replicas as needed

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_DB=lyve_db
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgresql_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      - DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    ports:
      - "8080:8080"
    volumes:
      - ./.docker/keycloak_data/:/opt/jboss/keycloak/standalone/data/

  blob-storage:
    image: minio/minio
    entrypoint: sh
    command: -c "mkdir -p /data/demo && minio server /data"
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    volumes:
      - ./.docker/blob_storage_data:/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgresql_data:
  keycloak_data:
  blob_storage_data:
