version: "3.8"

services:
  api:
    build:
      context: backend
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://user:password@mysql/db_name
      - RABBITMQ_URL=amqp://user:password@rabbitmq
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - rabbitmq
      - keycloak
      - redis

  media-server:
    image: your-media-server-image
    ports:
      - "4000:4000"
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq
    deploy:
      replicas: 3 # Adjust the number of replicas as needed

  frontend:
    build: ./frontend
    ports:
      - "19006:19006"
    environment:
      - REACT_APP_API_URL=http://api:3000
      - REACT_APP_WS_URL=ws://api:3000
      - REACT_APP_KEYCLOAK_URL=http://keycloak:8080/auth
      - REACT_APP_BLOB_STORAGE_URL=http://blob-storage:9000

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lyve_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  keycloak:
    command: ["start-dev"]
    image: quay.io/keycloak/keycloak:24.0.3
    environment:
      - DB_VENDOR=mysql
      - DB_ADDR=mysql
      - DB_DATABASE=lyve_db
      - DB_USER=user
      - DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  blob-storage:
    image: minio/minio
    entrypoint: sh
    command: -c "mkdir -p /data/demo && minio server /data"
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    volumes:
      - blob_storage_data:/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  blob_storage_data:
